force-app/main/default/objects/BreezyRouter__c/BreezyRouter__c.object-meta.xml
<CustomObject>
    <description>Stores the routers for the BreezyRouter app</description>
    <label>BreezyRouter</label>
    <nameField>
        <label>BreezyRouter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BreezyRouters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BreezyRouter_Member__c/BreezyRouter_Member__c.object-meta.xml
<CustomObject>
    <description>This stores all the members or users that belong to the particular BreezyRouter Router</description>
    <label>BreezyRouter Member</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>BreezyRouter Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BreezyRouter Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BreezyRouter_Member__c/fields/BreezyRouter__c.field-meta.xml
<CustomField>
    <fullName>BreezyRouter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Member lookup to the router</description>
    <inlineHelpText>Member lookup to the router</inlineHelpText>
    <label>BreezyRouter</label>
    <referenceTo>BreezyRouter__c</referenceTo>
    <relationshipLabel>BreezyRouter Members</relationshipLabel>
    <relationshipName>BreezyRouter_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/Routed_Date__c.field-meta.xml
<CustomField>
    <fullName>Routed_Date__c</fullName>
    <description>Datetime member was routed</description>
    <inlineHelpText>Datetime member was routed</inlineHelpText>
    <label>Routed Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/Routed_Time__c.field-meta.xml
<CustomField>
    <fullName>Routed_Time__c</fullName>
    <description>The time the member was routed</description>
    <inlineHelpText>The time the member was routed</inlineHelpText>
    <label>Routed Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>DIfferent member statuses in router</description>
    <inlineHelpText>DIfferent member statuses in router</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User lookup for Member</description>
    <inlineHelpText>User lookup for Member</inlineHelpText>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BreezyRouter_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BreezyRouter.cls
public class BreezyRouter {

    @InvocableMethod(label='Get Next User in BreezyRouter')
    public static List<Id> getNextUserInBreezyRouter(List<String> routerNames) {
        List<Id> nextUserIds = new List<Id>();

        if (routerNames != null && !routerNames.isEmpty()) {
            for (String routerName : routerNames) {
                Id nextUserId = getNextUserByRouterName(routerName);
                if (nextUserId != null) {
                    nextUserIds.add(nextUserId);
                }
            }
        }

        return nextUserIds;
    }

    private static Id getNextUserByRouterName(String routerName) {
        Id userId = null;
        
        List<BreezyRouter_Member__c> routerMembers = [SELECT UserId__c, Routed_Date__c, Routed_Time__c
                                            FROM BreezyRouter_Member__c
                                            WHERE Status__c = 'Active'
                                            AND BreezyRouter__r.Name = :routerName
                                            ORDER BY Routed_Date__c ASC, Routed_Time__c ASC
                                            LIMIT 1];
        
        if (!routerMembers.isEmpty()) {
            userId = routerMembers[0].UserId__c;
            
            Datetime now = Datetime.now();
            Time currentTime = now.time();
            routerMembers[0].Routed_Date__c = now ;
            routerMembers[0].Routed_Time__c = currentTime ;
            update routerMembers;
        }
        
        return userId;
    }
}