force-app/main/default/objects/BreezyRouter__c/BreezyRouter__c.object-meta.xml
<CustomObject>
    <description>Stores the routers for the BreezyRouter app</description>
    <label>BreezyRouter</label>
    <nameField>
        <label>BreezyRouter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BreezyRouters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BreezyRouter_Member__c/BreezyRouter_Member__c.object-meta.xml
<CustomObject>
    <description>This stores all the members or users that belong to the particular BreezyRouter Router</description>
    <label>BreezyRouter Member</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>BreezyRouter Member</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BreezyRouter Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BreezyRouter_Member__c/fields/BreezyRouter__c.field-meta.xml
<CustomField>
    <fullName>BreezyRouter__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Member lookup to the router</description>
    <inlineHelpText>Member lookup to the router</inlineHelpText>
    <label>BreezyRouter</label>
    <referenceTo>BreezyRouter__c</referenceTo>
    <relationshipLabel>BreezyRouter Members</relationshipLabel>
    <relationshipName>BreezyRouter_Members</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>DIfferent member statuses in router</description>
    <inlineHelpText>DIfferent member statuses in router</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>PTO</fullName>
            </value>
            <value>
                <fullName>On Leave</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BreezyRouter_Member__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User lookup for Member</description>
    <inlineHelpText>User lookup for Member</inlineHelpText>
    <label>UserId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>BreezyRouter_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BreezyRouterTest.cls
@isTest
private class BreezyRouterTest {
    @isTest static void testGetNextUserInBreezyRouter() {
        BreezyRouter__c routerRecord = new BreezyRouter__c(Name = 'TestQueue');
        insert routerRecord;

        BreezyRouter_Member__c routerMember = new BreezyRouter_Member__c(
            UserId__c = UserInfo.getUserId(),
            Status__c = 'Active',
            BreezyRouter__c = routerRecord.Id
        );
        insert routerMember;

        List<Id> nextUserIds = BreezyRouter.getNextUserInBreezyRouter(new List<String>{ 'TestQueue' });

        System.assertEquals(1, nextUserIds.size(), 'Found User in Router');
    }
}